### ISSUE TITLE
Enhance readme including some gifs

### ISSUE THREAD

**Issue by joseberlines** [bloomberg/ipydatagrid#190]
**a visual help in the Readme part is powerful**
The little brother of ipydatagrip -ipysheet- includes some nice gifs in the Readme part. It's so easy to get an idea of the capabilities of the repo just with 3 seconds look at it.

**Comment by jasongrout** [comment]
> includes some nice gifs in the Readme part

A link for convenience: https://github.com/QuantStack/ipysheet#ipysheet

**Comment by ibdafna** [comment]
Thank you - will address

**Comment by joseberlines** [comment]
Actually to be more precise even, the gifs could correspond to the examples in the examples folder.

**Comment by ibdafna** [comment]
> 
> 
> Actually to be more precise even, the gifs could correspond to the examples in the examples folder.

It would be ideal, but some of the examples are quite verbose, we'll need to alter them slightly so they're not overloading the page. Should be done in by Tuesday!

**Comment by joseberlines** [comment]
Cool. It was just an idea since the main point is giving the feeling with a first look that youcan show a d editorial a table in a jupyter notebook

**Comment by ibdafna** [comment]
All done! Let me know if there's anything else you'd like to see and thank you for taking the time to open this issue.
