### ISSUE TITLE
error installing jupyter labextension for ipywidgets

### ISSUE THREAD

**Issue by djinnome** [bloomberg/ipydatagrid#197]
**Describe the bug**
Installation of ipywidgets jupyter labextension fails.

**To Reproduce**
1. `$ pip install ipywidgets`
2. `$ jupyter labextension install  @jupyter-widgets/jupyterlab-manager ipydatagrid`
3. The following error occurred:

```bash
An error occured.
ValueError: "ipydatagrid" is not a valid npm package
See the log file for details:  /var/folders/z1/nhct2gps3y94tkbwqvvd7y_jw6p1l8/T/jupyterlab-debug-dse9w2rn.log
```

**Expected behavior**
I expected the installation to succeed without error messages

**Screenshots**
[jupyterlab-debug-dse9w2rn.log](https://github.com/bloomberg/ipydatagrid/files/6052253/bug.txt)

**Environment (please complete the following information):**
 - Operating System and Version: Mac OS X 10.14.6
 - Python version: 3.8.5  (anaconda3-2020.11)
 - Jupyter version: `$ jupyter --version`
 
```
jupyter core     : 4.6.3
jupyter-notebook : 6.1.4
qtconsole        : 4.7.7
ipython          : 7.19.0
ipykernel        : 5.4.3
jupyter client   : 6.1.7
jupyter lab      : 2.2.6
nbconvert        : 6.0.7
ipywidgets       : 7.6.3
nbformat         : 5.0.8
traitlets        : 5.0.5
```
**Additional context**
Please advise

**Comment by mbektasbbg** [comment]
@djinnome ipydatagrid is compatible with JupyterLab 3. Please follow the instructions in https://github.com/bloomberg/ipydatagrid#installation as well.

**Comment by ibdafna** [comment]
@djinnome Apologies - the instructions published initially were outdated. `pip install ipydatagrid` should be enough when using JupyterLab 3. It is important to note we only support JupyterLab3 for now!
