### ISSUE TITLE
Extra blank space at the bottom of the widget

### ISSUE THREAD

**Issue by fperez** [bloomberg/ipydatagrid#201]
FWIW I just checked on the binder link provided by the repo and I get the same effect, so at least you should be able to reproduce it easily...

![image](https://user-images.githubusercontent.com/57394/110716595-56800f80-81bc-11eb-93b7-decd6ec3aa5e.png)

**Comment by ibdafna** [comment]
@fperez I just tested locally and I am unable to reproduce the issue.  This is how I set up my environment:

```bash
conda create -n temp python=3.8
conda activate temp
pip install jupyterlab ipydatagrid==1.0.1
```

After that, running the snippet you provided above seems to work for me. I vaguely recall experiencing this problem when using the old `labextension` installation, despite re-running reinstalling JupyterLab and ipydatagrid. Can you try in a fresh environment and let me know if the issue still persists? I'll try with `virtualenv` on my end - could be related!

**Comment by fperez** [comment]
Good to know it works for you, thx for checking! Something is oddly broken with my conda setup b/c it won't let me make any new envs and right now I can't mess my system, so I'll have to wait.  I trust it's OK then, I suggest you close this one for now so it's not dangling... If I can replicate it later with a fresh env I can ping you to reopen.

**Comment by fperez** [comment]
Hi! I'm going to close the issue as I just updated to JLab 3.0.10 and ipydatagrid 1.0.2 and it now works, thanks!

The only weirdness I'm seeing is all that extra blank space at the bottom, not sure if that's intended or just on my system:

![image](https://user-images.githubusercontent.com/57394/110693318-288ad300-819c-11eb-8282-f1d0af4ea07b.png)

I'm putting it here in case it rings any bells, but I'll close the issue for now as the original problem is gone and I don't want to litter your repo :)

Thanks for the great tool!

**Comment by fperez** [comment]
FWIW I just checked on the binder link provided by the repo and I get the same effect, so at least you should be able to reproduce it easily...

![image](https://user-images.githubusercontent.com/57394/110716595-56800f80-81bc-11eb-93b7-decd6ec3aa5e.png)

**Comment by ibdafna** [comment]
@fperez really happy to hear it's working okay, thanks for keeping me in the loop!

The issue you are seeing with the blank space is the default canvas size. We don't have an intelligent way (yet) of determining a good default size for a given grid, so they all have the same one, and I agree it does look a bit odd for smaller grids. The good news is that this is a layout property and as such you pass it as a parameter to the grid constructor:

```python
from ipydatagrid import DataGrid
import pandas as pd

df = pd.DataFrame({"A":[1,2,3], "B":[4,5,6]})
grid = DataGrid(df, layout={"height":"120px", "width":"200px", "align-content":"center"})
grid
```

**Comment by gaborbernat** [comment]
@fperez opened https://github.com/bloomberg/ipydatagrid/issues/216 to track the extra space issue (a better solution than the workaround @ibdafna showed that is)
