### ISSUE TITLE
Command mode in jupyterlab

### ISSUE THREAD

**Issue by bdch1234** [bloomberg/ipydatagrid#203]
**Describe the bug**
Thanks for making a fantastic grid-widget! I am not sure if this is a bug or intended, but posting it anyway. After having made a selection in a grid, it seems that going into command mode in jupyter-lab does not work.

**To Reproduce**
1. Display a datagrid in jupyter lab
2. Select any of the cells
3. Press escape-key
4. Try using a command-mode button, such as add cell above with "a". Observe that nothing happens.

**Expected behavior**
Command mode work as usual.

**Comment by ibdafna** [comment]
Thanks for reporting. I think that happens because we use the esc key for deselections and probably prevent propagation after. Need to think about how to handle this better.

**Comment by ibdafna** [comment]
Resolved via #214
