### ISSUE TITLE
Large dataframe tabulation - slow initialisation/visualisation

### ISSUE THREAD

**Issue by bytesemantics** [bloomberg/ipydatagrid#204]
Hi

I have a use case where I want to be able to display large dataframes in an interactive table. 
My definition of 'large' is a frame of > 200k rows; 50 columns.

I have tried other table widgets (qgrid, ipyaggrid) - both struggle to render this dataframe size. ipyaggrid in particular takes an incredibly long time to render the table.

I was hoping for better performance from ipydatagrid  -> unfortunately performance appears very similar. Other than trying perspective-python (which I can't currently build :( ),  are there any suggestions for improving performance?

**Comment by gaborbernat** [comment]
Hello, can you please post a reproducible example of this? Thanks!

**Comment by ibdafna** [comment]
@bytesemantics I'd be keen to see a reproducible example as well! We wrote ipydatagrid with performance in mind. In fact, in this [example](https://github.com/bloomberg/ipydatagrid/blob/main/examples/DataGrid.ipynb) we render million cells to emphasize performance.

**Comment by gaborbernat** [comment]
I'll close this, for now, if we ever get a reproducible example of this I'm happy to reopen.

**Comment by ankostis** [comment]
See also #286
