### ISSUE TITLE
examples/CellEditing.ipynb - on_cell_changed does not fire from interactive edit

### ISSUE THREAD

**Issue by bytesemantics** [bloomberg/ipydatagrid#205]
When running examples/CellEditing.ipynb....

on_cell_changed() does fire when datagrid.set_cell_value() is called to change the grid.

on_cell_changed() does NOT fire when cell selected interactively and cell value changed

I also note that the data member datagrid.data  does reflect  the cell change - after datagrid.set_cell_value() is called
It does NOT reflect the cell change when the cell is edited interactively.

**Comment by ibdafna** [comment]
Thanks for reporting! #209 should fix this.

**Comment by ibdafna** [comment]
Closed via #209
