### ISSUE TITLE
How to deselect a selected row ?

### ISSUE THREAD

**Issue by bytesemantics** [bloomberg/ipydatagrid#206]
Clicking on a datagrid row -> selects the row  (assuming selection is set to 'row')  - this is natural expected UI behaviour.

However clicking on a selected row - does not toggle the selection - this is natural expected UI behaviour.
How should one deselect a selected row ?  (I've tried various combinations of key modifiers and mouse buttons).

**Comment by ibdafna** [comment]
You can deselect a row by hitting the esc key

**Comment by ibdafna** [comment]
Available in 1.0.4 🎉
