### ISSUE TITLE
Is it possible to wrap text in a cell? (i.e. several lines)

### ISSUE THREAD

**Issue by joseberlines** [bloomberg/ipydatagrid#210]
When rendering cells containing large texts  is it possible to wrap text in several lines?

**Comment by ibdafna** [comment]
It's not available yet, but it's coming very soon! Support was added to the underlying library we use in ipydatagrid, in this PR: https://github.com/jupyterlab/lumino/pull/140

**Comment by gaborbernat** [comment]
Seems that PR has been merged and released. Do we need to do anything to enable it?

**Comment by mbektasbbg** [comment]
@gaborbernat this feature is not in ipydatagrid yet. we need to update our @lumino/datagrid dependency and expose it via widget python interface to have it available in ipydatagrid.

**Comment by joseberlines** [comment]
But looks like it will come in the coming weeks!!! Cool thanks.

**Comment by ibdafna** [comment]
Available as of `ipydatagrid` 1.1.0. Enjoy! 😄 

Closed via #248
