### ISSUE TITLE
Format numeric columns

### ISSUE THREAD

**Issue by troelstk** [bloomberg/ipydatagrid#222]
Often I find myself in need of a way to format columns in a datagrid, such as setting the number of decimals. 

I'd like the datagrid to take as (optional) input a dict of columns and their respective formats, similar to column_widths. 
As far as I can see, that is not currently possible. 

The only alternative I have considered is to use the built-in round() function prior to creation of the datagrid.

**Comment by reckoner** [comment]
It's a keyword argument for `TextRenderer`, for example

`TextRenderer(format=".3f")`

**Comment by ibdafna** [comment]
Thank you @reckoner for answering this one. Closing but feel free to reopen if there's anything else.
