### ISSUE TITLE
Use `on_cell_change` (or other callbacks) for data input validation?

### ISSUE THREAD

**Issue by reckoner** [bloomberg/ipydatagrid#224]
**Is your feature request related to a problem? Please describe.**

Given that a user can input a new value into a cell, is it possible to use the callback infrastructure to prevent invalid inputs such as out of bounds  numbers or invalid types?

**Describe the solution you'd like**

Some way to do input validation on cells.

**Describe alternatives you've considered**
N/A
**Additional context**
N/A

**Comment by ibdafna** [comment]
Hi @reckoner 👋 

The front-end of `ipydatagrid` (lumino) has some built in data validation based on the column data type, but nothing more than that. @mbektasbbg is there anything else we do on that front to validate data?

The `on_cell_change` event occurs after a cell has been changed, so it's probably not the most appropriate place to implement checking. You could probably still use `on_cell_change` to do some data validation such that if a given value is above the maximum, for example, you set the cell value to the maximum value via the python API. That should work, I think.

**Comment by reckoner** [comment]
How does this avoid an infinite recursion if I listen for the `on_cell_change` and then somehow fix it in the Python and then triggered the same callback again?

**Comment by ibdafna** [comment]
You won't end up with an infinite recursion because that callback will be triggered again *only* if the new value violates your condition. And because you implement the logic for validation, you will make sure to send a new value which adheres to the specifications of your constraints.

Here is an example:
```python
import pandas as pd
from ipydatagrid import DataGrid


# Not allowing any values greater than 10.
# Values greater than 10 will be capped at 10.
def on_change(e):
    val = e['value']
    col = e['column']
    row = e['row']
    if (val > 10):
        grid.set_cell_value_by_index(col, row, 10)
        
click_df = pd.DataFrame({'Col1': [10, 6, 7, 2]})
grid = DataGrid(click_df,
                layout={'height':'150px'}, 
                editable=True, 
                selection_mode="row", 
                base_column_size=100,
                base_row_size=30)

grid.on_cell_change(on_change)
grid
```

**Comment by reckoner** [comment]
thank you for the detailed example!

**Comment by joseberlines** [comment]
Please include the above piece of code as another example in the collection and name it "call backs when changing cells". Thanks.
