### ISSUE TITLE
How to add or remove a row?

### ISSUE THREAD

**Issue by marcmenem** [bloomberg/ipydatagrid#229]
Its great to see this library open sourced!

I have not found in the examples a way to add or remove rows from a grid. 
I am using the grid for a user to enter weights of a different assets, but I would the user to be able to add more assets or remove them.

**Comment by ibdafna** [comment]
Hello @marcmenem 👋 

`ipydatagrid` was initially designed to be a view of a given data model, with the idea that the dimensions of the data model do not change (although the data in model itself can be mutable). Unfortunately this means that there is no API to add or remove rows. However, the good news is that we can probably achieve behaviour that with a bit of interop with `ipywidgets`. I have something in mind, but before it can work, I'll need to make some changes to the internal messaging API so that we do not cache the dimensions of the data model when cells are edited. I'll update this thread in the next couple of weeks.

**Comment by marcmenem** [comment]
Thanks for looking into it. 
As a simple workaround, I just retrieved the dataframe, added a row, and set it back to the DataGrid object

**Comment by joseberlines** [comment]
But if the tables are not so big the way to go is changing the data and rendering the whole table again, right? Actually I was thinking about the same and always thought about having a kind MVC approach when the data changes the table is rendered again. Is there any hook to this approach?

**Comment by ibdafna** [comment]
Retrieving the DataFrame and adding/deleting a row is exactly how I would approach this. The only thing which prevents this from working properly is when a change is made to the data model (if you edit a cell for example) on one of the added rows as we keep a cache of the row indices for performance reasons. If the row indices change (which they do if we add remove/rows) then it could cause an issue. I'll fix this very soon and add to the next release.

**Comment by ibdafna** [comment]
The issues with the data model mentioned above have been resolved in `ipydatagrid` 1.0.5. The following example should work for what you need, but do let me know if something doesn't work as expected!

```python
import pandas as pd
import ipydatagrid as dg
import ipywidgets as ipw

## Callbacks ##
def add_row(e):
    current_grid_df = grid.get_visible_data()
    additional_row = pd.DataFrame(
        columns = current_grid_df.columns, 
        index = [current_grid_df.index[-1] + 1],
        data = "" * len(current_grid_df.columns)
    )
    grid.data = current_grid_df.append(additional_row, ignore_index=True)
    
def remove_row(e):
    current_grid_df = grid.get_visible_data()
    grid.data = current_grid_df.drop(current_grid_df.tail(1).index)

## Data ##
df = pd.DataFrame(data={"Col1":range(1,11), "Col2":range(11,21)})

## Widgets ##
grid = dg.DataGrid(df, selection_mode='cell', editable=True, layout={"height":"350px"})
button_add_row = ipw.Button(description="Add Row", 
                            style=ipw.ButtonStyle(button_color='darkgreen'))
button_remove_row = ipw.Button(description="Remove Row", 
                               style=ipw.ButtonStyle(button_color='darkred'))

## Handlers ##
button_add_row.on_click(add_row)
button_remove_row.on_click(remove_row)

## Layout ##
ipw.VBox([
    ipw.HBox([button_add_row, button_remove_row]),
    grid
])
```

**Comment by Ernst79** [comment]
I tried the above script, but it only allows me to delete rows, the add row button doesn't work. Has something changed?

**Comment by martinRenou** [comment]
This seems to be a change in the Pandas API.

Citing [this stackoverflow post](https://stackoverflow.com/questions/75956209/error-dataframe-object-has-no-attribute-append):

> As of pandas 2.0, append (previously deprecated) [was removed](https://pandas.pydata.org/docs/whatsnew/v2.0.0.html#removal-of-prior-version-deprecations-changes).
> You need to use [concat](https://pandas.pydata.org/docs/reference/api/pandas.concat.html) instead (for most applications):
> ```python
> df = pd.concat([df, pd.DataFrame([new_row])], ignore_index=True)
> ```

**Comment by Ernst79** [comment]
Thanks, that works!
