### ISSUE TITLE
how to avoid extra space in the botton of a cell in a notebook when rendering

### ISSUE THREAD

**Issue by joseberlines** [bloomberg/ipydatagrid#271]
**Describe the bug**
When rendering a grid sometimes after the ipydatagrid object there is a big blank space

**To Reproduce**
![image](https://user-images.githubusercontent.com/33203439/131880343-fa67643f-d319-45f6-ba86-37364375786a.png)

**Expected behavior**
the following cells appears right after the grid

**Comment by ibdafna** [comment]
You can pass a `layout` object as an argument to the constructor: `layout={"height": "90px"}`. This [example](https://github.com/bloomberg/ipydatagrid/blob/main/examples/Column%20Width%20Auto-Fit.ipynb) has a a full code snippet.
