### ISSUE TITLE
Question: is ipydatagrid thought for displaying html

### ISSUE THREAD

**Issue by joseberlines** [bloomberg/ipydatagrid#289]
**colors in cells**
ofthentimes you want to display text with different colors in cells

** use html
An option would be to be able to add html in a cell

**Comment by ibdafna** [comment]
Hey @joseberlines We support different text colors in cells. Look at the TextRenderer examples:

https://github.com/bloomberg/ipydatagrid/blob/main/examples/DataGrid.ipynb
