### ISSUE TITLE
change the size of the index columns in ipydatagrid <- Not working after the update

### ISSUE THREAD

**Issue by jaewon4067** [bloomberg/ipydatagrid#320]
I got the code from the example project in BQuant called 'ipydatagrid Tutorial & Migration Guide', and I tried to run the code and it's no longer working and got me an error. 

![image](https://user-images.githubusercontent.com/58613244/164214549-ad44c560-54a0-44d2-b6dd-ccd24fd73c68.png)

And then I got an error :
 
![image](https://user-images.githubusercontent.com/58613244/164214721-08bd9693-f5bd-4f7b-810d-37cf3413fa6a.png)

The main issue here is this part:
column_widths = {('Ticker', ''): 220, ('Name', ''): 180, ('Sector', ''):140}
This used to work with the previous version but not anymore. It says this doesn't support tuple anymore. Am I doing something wrong here, any ideas? Thank you :)

I will attach the code so that you guys can try:

import bql
import ipydatagrid
import ipywidgets as widgets
import pandas as pd
from bqplot import ColorScale, Scale
from IPython.display import display
from numpy import nan, isnan
from numpy.random import randint

bq = bql.Service()

univ = bq.univ.members('INDU Index')
analysis_period = 'LTM'

name = bq.data.name()
sector = bq.data.gics_sector_name()

rev_growth = bq.data.sales_growth(analysis_period)
earnings_growth = bq.data.normalized_net_income_growth(analysis_period)
fcf_growth = bq.data.free_cash_flow_1_year_growth(analysis_period)

column_names = {
    'Name': name,
    'Sector': sector,
    'Sales Growth': rev_growth,
    'Earnings Growth': earnings_growth,
    'Free Cash Flow Growth': fcf_growth,
    }

request = bql.Request(univ, column_names)
response = bq.execute(request)

stock_data = pd.concat(objs=[field.df()[field.name] for field in response],
                       axis=1,
                       sort=False)
stock_data.index.name = 'Ticker'
stock_data.sort_values(by='Ticker', axis=0, inplace=True)

new_columns = [('Company', 'Name'),
               ('Company', 'Sector'),
               ('LTM Fundamentals', 'Sales Growth'),
               ('LTM Fundamentals', 'Earnings Growth'),
               ('LTM Fundamentals', 'Free Cash Flow Growth'),
              ]

multi_index_columns = pd.MultiIndex.from_tuples(new_columns)
stock_data_nested = pd.DataFrame(data=stock_data.to_dict())
stock_data_nested.columns = multi_index_columns
stock_data_nested.index.name = 'Ticker'
nested_sample = stock_data_nested.head()
pinned_df = nested_sample.reset_index()
pin_columns = [('Ticker', ''), ('Company', 'Name'), ('Company', 'Sector')]
pinned_df.set_index(keys=pin_columns, inplace=True)

column_widths = {('Ticker', ''): 220, ('Name', ''): 180, ('Sector', ''):140}
pinned_df.index.names = ['Ticker', 'Name', 'Sector']                   # <-- the code will fail without this line
pinned_grid = ipydatagrid.DataGrid(dataframe=pinned_df,
                                   base_column_header_size=40,
                                   base_column_size=150,
                                   column_widths = column_widths,
                                   layout={'height': '210px'})

pinned_grid

**Comment by pablo2207** [comment]
I have te same issue, it doesn't work for multiindex columns. Can you pls solve this issue?

pandas=1.3.5.
ipydatagrid=1.1.11 and 1.1.12

**Comment by ibdafna** [comment]
@jaewon4067 for any BQuant related issues - including ipydatagrid - please contact the Bloomberg help desk. I would also ask that you refrain from posting internal BQuant code on public platforms to avoid confusion.

@pablo2207 A fix was released and the issue was confirmed not present in 1.1.12. If you do experience issues with 1.1.12, would you be able to post a reproducible code snippet here along with the output of `conda list` or `pip freeze` of your environment?

Many thanks,
Itay

**Comment by pablo2207** [comment]
> @jaewon4067 for any BQuant related issues - including ipydatagrid - please contact the Bloomberg help desk. I would also ask that you refrain from posting internal BQuant code on public platforms to avoid confusion.
> 
> @pablo2207 A fix was released and the issue was confirmed not present in 1.1.12. If you do experience issues with 1.1.12, would you be able to post a reproducible code snippet here along with the output of `conda list` or `pip freeze` of your environment?
> 
> Many thanks, Itay

Sorry, I just checked locally and the package works fine but the problem occurs in BQuant and the Bloomberg help desk claims the problem is with ipydatagrid package. So, they can't help...

**Comment by jaewon4067** [comment]
> @jaewon4067 for any BQuant related issues - including ipydatagrid - please contact the Bloomberg help desk. I would also ask that you refrain from posting internal BQuant code on public platforms to avoid confusion.
> 
> @pablo2207 A fix was released and the issue was confirmed not present in 1.1.12. If you do experience issues with 1.1.12, would you be able to post a reproducible code snippet here along with the output of `conda list` or `pip freeze` of your environment?
> 
> Many thanks, Itay

**Comment by jaewon4067** [comment]
> @jaewon4067 for any BQuant related issues - including ipydatagrid - please contact the Bloomberg help desk. I would also ask that you refrain from posting internal BQuant code on public platforms to avoid confusion.
> 
> @pablo2207 A fix was released and the issue was confirmed not present in 1.1.12. If you do experience issues with 1.1.12, would you be able to post a reproducible code snippet here along with the output of `conda list` or `pip freeze` of your environment?
> 
> Many thanks, Itay

Hi Itay, thank you for your reply. I actually came from the Bloomberg help desk and they suggested me to open up a new issue here with the link. Should I ask the Bloomberg help desk again or could you please let me know if there's a better way? Thank you again!

I deleted the internal BQuant code, sorry about that.

Jaewon

**Comment by ibdafna** [comment]
> 

Hey Jaewon - thanks for deleting the BQuant code. The help desk should get in touch this week to clarify any misunderstanding. Please do raise any issues or enhancement requests with them and they should be able to help.

Thanks,
Itay
