### ISSUE TITLE
Selection changed

### ISSUE THREAD

**Issue by Mark-Caple** [bloomberg/ipydatagrid#335]
I have looked around but cannot find a way of creating a handler for when a cell, row or column selection changes. Is this possible?

Basically I want to do something on one of these events. So if a new row is selected I want to be able to do something.

**Comment by ibdafna** [comment]
Hello @Mark-Caple 🙋‍♂️and welcome to the `ipydatagrid` community!

This is possible, yes. See code snippet below:

```python
import ipydatagrid
import pandas as pd
import numpy as np
import ipywidgets as widgets

grid = ipydatagrid.DataGrid(pd.DataFrame([1,2,3,4]), selection_mode="row", layout={"height":"140px"})

def callback(e):
    print(e)
    
grid.observe(callback, names='selections')
grid
````

I will look into revamping the examples folder so it's highlighted there.

**Comment by Mark-Caple** [comment]
Unfortunately @ibdafna  this does not work with Jupyter Notebook. I simply copy and pasted into a cell, executed the cell and the DataGrid appears but clicking on a row does not print anything.

![Screenshot from 2022-08-18 15-02-44](https://user-images.githubusercontent.com/107525651/185298329-7564186b-2b63-4447-a7fa-196335abc9ab.png)

![Screenshot from 2022-08-18 15-03-30](https://user-images.githubusercontent.com/107525651/185298353-348508fa-0f8c-4486-b352-6431033dcf7b.png)

**Comment by ibdafna** [comment]
@Mark-Caple it's just how ipywidgets work. You'll need an [output widget](https://ipywidgets.readthedocs.io/en/stable/examples/Output%20Widget.html) to capture the stdout output generated by the code. This is done for you in JupyterLab (where I tested this)

```python
import ipydatagrid
import pandas as pd
import numpy as np
import ipywidgets as widgets
from IPython.display import display

out = widgets.Output()
grid = ipydatagrid.DataGrid(pd.DataFrame([1,2,3,4]), selection_mode="row", layout={"height":"140px"})
display(out)
@out.capture()
def callback(e):
    print(e)
    
grid.observe(callback, names='selections')
grid
```

**Comment by Mark-Caple** [comment]
Perfect @ibdafna . Sometimes difficult to see the woods from the trees. Has been a long time since I've worked with notebooks but a 3rd party tool requires that I do so  :+1:

**Comment by ibdafna** [comment]
@Mark-Caple this is valid feedback, thank you! I think us maintainers often tend to forget just how complex the widget system has become, and so it's tough for users to keep up with the changes. The solution is more elaborate documentation with examples that span beyond the bounds of the specific widget package. We are in the process of rewriting the documentation and I will definitely keep this in mind.
