### ISSUE TITLE
Issues when using ipydatagrid with Mercury / nbconvert

### ISSUE THREAD

**Issue by pplonski** [bloomberg/ipydatagrid#338]
The [`Mercury`](https://github.com/mljar/mercury) is a framework for converting Jupyter Notebooks into web applications with YAML header. It is based on the `nbconvert` tool. It collects parameters from the user interface and executes the notebook with new parameters with `nbconvert`. The final HTML is displayed in the web browser for the user.

One of my users has an issue with the `ipydatagrid` package. Details https://github.com/mljar/mercury/issues/159

He is using the following code:

```py
from ipydatagrid import DataGrid
import numpy as np 
import pandas as pd 

df = pd.DataFrame(data=np.random.randn(5,10))
datagrid=DataGrid(df)
datagrid
```

Is the `ipydatagrid` working with the `nbconvert` tool? Can I export notebooks with `ipydatagrid` to HTML files? When I tried the above code, I got:

![image](https://user-images.githubusercontent.com/6959032/188079694-3d6b9ada-7909-493e-9ad5-2e8b135ccfab.png)

The notebook was exported with the command:

```
jupyter notebook --to html grid.ipynb
```

If the `ipydatagird` will work with `nbconvert`, it will work with `Mercury` as well.

**Comment by jonyow** [comment]
I've also run into the same issue, with ipydatagrid not rendering with Jupyter Notebooks exported to HTML. It did also used to work for me until recently.

The notebook was exported using:   jupyter nbconvert --to html

This was the error I get:

Failed to create view for 'DataGridView' from module 'ipydatagrid' with model 'DataGridModel' from module 'ipydatagrid'
TypeError: c.JupyterPhosphorPanelWidget is not a constructor
    at g._createElement (https://cdn.jsdelivr.net/npm/ipydatagrid@%5E1.1.11/dist/index.js:2:997709)

Any help would be much appreciated!

**Comment by ibdafna** [comment]
Thank you for reporting - we will investigate!

**Comment by martinRenou** [comment]
> Failed to create view for 'DataGridView' from module 'ipydatagrid' with model 'DataGridModel' from module 'ipydatagrid'
TypeError: c.JupyterPhosphorPanelWidget is not a constructor

It's probably pulling ipywidgets 8?

**Comment by jonyow** [comment]
> 

If it helps, I'm using ipywidgets 7.7.0 when encountering the error above.

**Comment by martinRenou** [comment]
Just in case, can you try with 7.7.2? I wonder if there is an issue with older ipywidgets that could be pulling the front-end HTMLManager for ipywidgets 8 which would be incompatible.

**Comment by jonyow** [comment]
it's the same on 7.7.2:

![image](https://user-images.githubusercontent.com/1131871/188603458-fc669a26-54b9-4049-b6f9-6e3f6c847ed7.png)

**Comment by martinRenou** [comment]
Can you try running nbconvert with the option `--HTMLExporter.html_manager_semver_range="0.20.2"`?

**Comment by jonyow** [comment]
yes, that's working for me now! Thanks very much for the quick response and for open sourcing such an useful package!
