### ISSUE TITLE
Text not wrapping, how to proceed?

### ISSUE THREAD

**Issue by joseberlines** [bloomberg/ipydatagrid#355]
**Describe the bug**
I would like that when displaying a datagrid the text is wrapped

This is the code:

```
import ipydatagrid as grid
import pandas as pd

li = [['lorem','ipsum', 'rosae rosae long long '],['lorem','sfs/ df', 'rosae rosae'],['lorem','sfsd/df', 'rosae rosae'],['er/er','ipsum', 'rosae rosae'],['er/er','ipsum', 'rosae rosae'],['er er','ipsum', 'rosae rosae']]
df = pd.DataFrame(li)
default_renderer = grid.TextRenderer(
    background_color=grid.VegaExpr("cell.value <= 0.5 ? 'pink' : 'lawngreen'"),
    text_elide_direction="left",
    text_wrap=True) 

datagrid = grid.DataGrid(df, editable=True, default_renderer=default_renderer)
datagrid
```
The result is as follows in the screenshot and the text is not wrapped in several lines despite of the text_wrap = True nor the columns are autoscaled in lenght.
Does anyone know how to proceed?
![image](https://user-images.githubusercontent.com/33203439/195853744-4bdc204c-ffdf-414b-97f7-77376b460d0f.png)

**Comment by joseberlines** [comment]
Could someone point to a repo/github gist / whatever using ipydatagrid in which indeed the text within the cells is wrapped in several lines?
thanks

**Comment by martinRenou** [comment]
You already opened an issue for this https://github.com/bloomberg/ipydatagrid/issues/294.

Text wrapping is not implement for the body of the grid. This is a missing feature from Lumino, not an ipydatagrid issue. We can close it here. Please open an issue on the Lumino repository https://github.com/jupyterlab/lumino, we can continue the discussion there.
