### ISSUE TITLE
Version of ipydatagrid in pypi 1.1.12 in github 1.1.11

### ISSUE THREAD

**Issue by joseberlines** [bloomberg/ipydatagrid#361]
I see in pypi the lastest ipydatagrid version is 1.1.12:
https://pypi.org/search/?q=ipydatagrid

but here in github the last version is 1.1.11

Can someone explain?

Thanks

**Comment by ibdafna** [comment]
@joseberlines We forgot to add a release on the GitHub page - this is fixed now!
