### ISSUE TITLE
NaN are not displayed correctly when format is specified in TextRender

### ISSUE THREAD

**Issue by gioxc88** [bloomberg/ipydatagrid#368]
if I have nan in the dataframe of even NaT for dates, there is no way to change the display value for these cells.
There is a parameter called `missing` in the `TextRenderer` but it does nothing
is there an alternative way to specify the value for NaN?
Thanks 

![image](https://user-images.githubusercontent.com/41852601/199720027-86a80ec1-9110-4b4a-8f96-c5f9030bb271.png)

```
import numpy as np
import pandas as pd
from ipydatagrid import DataGrid, TextRenderer

df = pd.DataFrame(np.random.uniform(size=(10, 2)))
df.iloc[0, 1] = np.nan
DataGrid(
    df,
    default_renderer=TextRenderer(
        format='.2f',
        missing='-'
    )
)
```

**Comment by gioxc88** [comment]
up

**Comment by martinRenou** [comment]
You can use a conditional formatter using the `Math.isNan` function:

Using a Vega expression:

```python
from ipydatagrid import VegaExpr, TextRenderer

TextRenderer(
    text_value=VegaExpr("Math.isNan(cell.value) ? '-' : cell.value")
)
```

Using a Python expression:

```python
from ipydatagrid import Expr, TextRenderer

TextRenderer(
    text_value=Expr("'-' if Math.isNan(cell.value) else cell.value")
)
```

**Comment by tfmark** [comment]
The following code works (VegaExpr or Expr) to replace NaN with a hyphen:

```py
import ipydatagrid
import pandas as pd
import numpy as np

ipydatagrid.DataGrid(
    dataframe=pd.DataFrame({"a":[np.nan, 2, 3], "b":[4, np.nan, 6], "c":[7, 8, np.nan]}),
    renderers=dict(
        a=ipydatagrid.TextRenderer(text_value=ipydatagrid.VegaExpr("isNaN(cell.value) ? '-' : cell.value")),
        b=ipydatagrid.TextRenderer(text_value=ipydatagrid.Expr("cell.value if isValid(cell.value) else '-'")),
    ),
)
```
![image](https://github.com/bloomberg/ipydatagrid/assets/80677094/37e2e539-66a0-4ddf-aa3e-6bd1927e55f2)

I think this issue can be closed.
