### ISSUE TITLE
Impossible to format dates using Expr (please provide example of how to do it )

### ISSUE THREAD

**Issue by gioxc88** [bloomberg/ipydatagrid#372]
I tried multiple times to format datetime because I want to avoid displaying NaT and I find it impossible despite trying in many different ways.
If it wasn't for NA I could have just used `TextRenderer(format='%Y%B%d', format_type='time')`

Here is a simple example:

```
import pandas as pd
from ipydatagrid import TextRenderer, DataGrid
from py2vega.functions.type_coercing import toDate
from py2vega.functions.formatting import timeFormat, timeParse
from py2vega.functions.type_checking import isValid, isDate, isString


def format_date(cell):
    if not isValid(cell.value):
        return '-'
    else:
        return timeFormat(toDate(cell.value), '%Y%B%d')

    
date = pd.date_range(start='20221010', periods=10, name='date').to_frame().reset_index(drop=True)
date.iloc[0,0] = np.nan


DataGrid(
    date,
    default_renderer=TextRenderer(text_value=Expr(format_date))
)
```

**Comment by martinRenou** [comment]
Unfortunately your approach here cannot work. It's a bit non-intuitive but your `format_date` function will not be executed in the Python process but in the JavaScript process, so you cannot rely on pandas functions there.

Instead your `format_date` can only be a valid Vega expression, see https://vega.github.io/vega/docs/expressions. You have functions available like `isDate` available in Vega expressions that you can use.

**Comment by gioxc88** [comment]
> here cannot wo

I am not using any pandas function in `from_date` If I do it with `VegaExpr` the result is the same. I doesn't display anything.
I think this is a bug

**Comment by martinRenou** [comment]
Really sorry, too much context switching made me read your issue too fast.

It looks like you found a proper issue. Looking into it.

**Comment by gioxc88** [comment]
> Really sorry, too much context switching made me read your issue too fast.
> 
> It looks like you found a proper issue. Looking into it.

Thanks a lot for looking into it!

**Comment by martinRenou** [comment]
Really surprised this has not been reported before 😅 This should fix https://github.com/bloomberg/ipydatagrid/pull/373

**Comment by gioxc88** [comment]
Oh wow, so fast!!!
Thanks a lot. I guess it's gonna be in available in the next release?
Thanks
