### ISSUE TITLE
Ipydatagrid does not work with voila==4.0.0 and jupyterlab==3.6.3

### ISSUE THREAD

**Issue by jobinnthomas** [bloomberg/ipydatagrid#421]
Ipydatagrid does not display anything with viola==4.0.0 and jupyterlab==3.6.3. 
I got jupyterlab to run the ipydatagrid to display properly but when i try to run it with viola, it does not display the grid. 
Is there any way to fix ?
Here is my requirements file.

jupyterlab==3.6.3
voila==0.4.0
ipydatagrid==1.1.15
ipywidgets ==8.0.2
nbconvert==7.4.0
ipykernel==6.23.1

**Comment by vthemelis** [comment]
Hi, do you have any error logs on your JS console?

**Comment by jobinnthomas** [comment]
You can close this....the below seems to work...I am not sure about jupyter lab but I am guessing that should work as with close to below.

notebook==7.0.8
voila==0.5.5
ipywidgets==8.1.1
ipydatagrid==1.2.1
ipynb==0.5.1****

**Comment by rootsmusic** [comment]
Great @jobinnthomas!  You can close your own issues by clicking on "close issue" (button next to "comment" at the bottom).
