### ISSUE TITLE
Filter/sort controls not selectable in latest version

### ISSUE THREAD

**Issue by zwelz3** [bloomberg/ipydatagrid#446]
**Describe the bug**
Filter/sort controls not selectable in latest `ipydatagrid` release. 

**To Reproduce**
1. Install `ipydatagrid==1.2.0`
2. Run default [DataGrid.ipynb](https://github.com/bloomberg/ipydatagrid/blob/main/examples/DataGrid.ipynb) example
3. Try to click on the filter/sort icon for a column
4. Observe no UI is triggered for filter/sort column

**Expected behavior**
Prior to `1.2.0` clicking the column icon would open a UI (see below)

![image](https://github.com/bloomberg/ipydatagrid/assets/32652349/d4ccb4ef-1f8d-47cc-928d-3dca01a1d854)

**Environment (please complete the following information):**
 - Operating System and Version: Windows 10 Enterprise Version 10.0.19045
 - Browser [e.g. Firefox, Safari] (if applicable):- Chrome Version 116.0.5845.180 (Official Build) (64-bit)

**Comment by jgunstone** [comment]
just double checked this and have the same problem - 
the version on binder isn't working in the way described

**Comment by aloneguid** [comment]
same here!

**Comment by kaizenloop** [comment]
Also having this issue in the same way described

**Comment by aloneguid** [comment]
I had to downgrade to previous version, works fine.

**Comment by martinRenou** [comment]
I think we need to revert https://github.com/bloomberg/ipydatagrid/pull/441 for a patch release as it seems to have broken the button entirely.

**Comment by neexa** [comment]
It seems to be solved with the latest Jupyterlab version (4.0.10)

**Comment by ywahl** [comment]
When will this PR be included in a next official release?

**Comment by martinRenou** [comment]
When https://github.com/bloomberg/ipydatagrid/pull/469 gets merged :)

**Comment by cmc-emmet** [comment]
@martinRenou  - given that we're now at version 1.3.1 has this Issue been resolved?

**Comment by martinRenou** [comment]
Indeed, this has been resolved in the latest release 1.3.0, 1.3.1 should come soon with other bug fixes.

Thanks!
