### ISSUE TITLE
Nested hierarchies with common entries on level 1 cause issues

### ISSUE THREAD

**Issue by MDDietz2** [bloomberg/ipydatagrid#459]
**Describe the bug**
Using "display" on a dataframe with MultiIndex rows merges common entries only if they are on Level0 of the DataFrame. DataGrid seems to try and merge entries on Level 1 and thereafter which causes some odd looking graphics and render problems - in particular if I change the width of  columns 

**To Reproduce**
1. Use example in    [examples/Nested Hierarchies.ipynb](https://github.com/bloomberg/ipydatagrid/blob/0354a4d66c5c1298895026cec7d99bdb360914c1/examples/Nested%20Hierarchies.ipynb#L33)
2. Flip the levels and adjust base_column_size:
```
row_bottom_level = ["Sector 1", "Sector 1", "Sector 2", "Sector 2"]
row_top_level = ["Security A", "Security B", "Security C", "Security D"]

base_column_size=120,
```
3. See error.
4. Visual gets worse if I move column width between the two row index columns around

**Expected behavior**
Do not try and merge for Level 1 and thereafter.
Fix display error.
Add a parameter so user can switch of merging cells in the row multiindex

**Screenshots**
![image](https://github.com/bloomberg/ipydatagrid/assets/95041320/49367278-86fd-4efe-b008-c948b4dc3586)

**Comment by MDDietz2** [comment]
See #311 which was closed and not merged. Any particular reason?

**Comment by MDDietz2** [comment]
I believe this is a bug here:
https://github.com/bloomberg/ipydatagrid/blob/0354a4d66c5c1298895026cec7d99bdb360914c1/js/core/viewbasedjsonmodel.ts#L68-L70

This should be "mergedRowLocations" - validates if there is an issue in the merging structure and - if True - removes merging. However, currently the check for rows is done on the columns currently. Should be:
```
    if (!ArrayUtils.validateMergingHierarchy(mergedRowLocations)) {
      mergedRowLocations = [];
    }
```
It's fixed in the PR above but not merged.

**Comment by TermeHansen** [comment]
I still see this issue. If there indeed is a fix in the PR mentioned above, why is this bug then still here?

![Screenshot from 2024-02-29 10-52-20](https://github.com/bloomberg/ipydatagrid/assets/6922018/2269346c-6016-46c1-99ea-0eeab39149c0)

![image](https://github.com/bloomberg/ipydatagrid/assets/6922018/ef77f000-3b48-4a7a-9237-da4f1d082361)

**Comment by martinRenou** [comment]
Fixed by https://github.com/bloomberg/ipydatagrid/pull/489
