### ISSUE TITLE
VScode doesn't display Datagrid

### ISSUE THREAD

**Issue by f3rn4nd0-c354r** [bloomberg/ipydatagrid#465]
Hello,
I usually use VScode to edit my notebooks, but the DataGrid widget is not displayed correctly.
I didn't find much information about it, but I did find this: https://github.com/microsoft/vscode-jupyter/wiki/IPyWidget-Support-in-VS-Code-Python

Use of [Widgets](https://jupyter.org/widgets) require us to download supporting files from a 3rd party website. The 3rd party websites are as follows:

[jsDelivr](https://jsdelivr.com/)
[UNPKG](https://unpkg.com/)

Can you help me configure VScode to display this widget correctly?

Thanks,

**Comment by jobinnthomas** [comment]
[requirements.txt](https://github.com/bloomberg/ipydatagrid/files/14131938/requirements.txt)
This requirement file versions displays the grid properly in vscode although i was having issues with viola . I have not troubleshot viola.

**Comment by jobinnthomas** [comment]
> > pypiserver==1.4.2
> > pytest==7.1.2
> > notebook==6.5.2
> > voila==0.3.6
> > ipywidgets==7.7.1
> > matplotlib==3.6.2
> > ipydatagrid==1.1.15
> > ipynb==0.5.1
> > plotly==5.14.1
> > pyperclip==1.8.2
> 
> @jobinnthomas These requirements were for ipydatagrid==1.1.15.

Correct...i have only gotten ipywidgets and ipydatagrid to work with these version in VSCode 1.82 version. However I have not spend much time testing with newer versions. If anything does work, please post

**Comment by jobinnthomas** [comment]
Hi this works with VSCODE 1.86.2. I am able see ipywidets, ipydatagrid and viola without any issues.
notebook==7.0.8
voila==0.5.5
ipywidgets==8.1.1 
ipydatagrid==1.2.1
ipynb==0.5.1  

[requirements.txt](https://github.com/bloomberg/ipydatagrid/files/14304727/requirements.txt)

**Comment by f3rn4nd0-c354r** [comment]
Yes, thanks!
Haven't been around much.
