### ISSUE TITLE
Column width is reverting back to defaults randomly after updating the data in the datagrid

### ISSUE THREAD

**Issue by jobinnthomas** [bloomberg/ipydatagrid#472]
#### **Describe the bug**
If i initialize a datagrid and then add columns and rows to it by replacing the data, then the column width property is not maintained.
This happens randomly which is the weird behavior....I am using Vscode 1.78.2.
This is my requirements file 
[requirements.txt](https://github.com/bloomberg/ipydatagrid/files/14128871/requirements.txt)

 
```
# Code Example is below. This code runs and displays in Vscode
# Lets say i initialize a datagrid.
  
import ipydatagrid as ipygrid
from ipydatagrid import Expr, TextRenderer
import pandas as pd
import ipywidgets as widgets  

# initializing the data grid.
df = pd.DataFrame(data={"Index": [''], "RepeatIndex": ['']}, index=["Index", "RepeatIndex"])  # Assuming a single value
maingrid = ipygrid.DataGrid(df, selection_mode='cell', editable=True, layout=widgets.Layout(
    width="2000px", height="500px", margin='0px 0px 0px 0px'))
maingrid.auto_fit_columns = True
maingrid.auto_fit_params = {"area": "all"}

# Then I display it
display(maingrid)
 
#  Then i add columns to it
header = 'Index,RepeatIndex,Error,Channel,Input,Coupling,Bandwidth,VdivGainTable,VdivPreviousGainTable,TypeofVdiv,VdivApplied,Gain,GainErrorPercent,OffsetError,OffsetErrorPercent,VgaCode,GainCurveCal,GainOffsetCal,CurveSpec,VinPoints,VoutPoints,FeGainEffect,GainErrorLimit,OffsetErrorLimit,ResidualDCAccuracyLimit,ResidualBowTieLimit'
columns = []   
for x in header.split('\n'):
    if len(x) > 10:
        columns.append(x.split(','))
df = pd.DataFrame(columns=columns)
df.set_index('Index', inplace=True)
maingrid.data = df


# Then i add rows to it by appending to existing data
newrow = '11,0,False,4,INPUTA,DC50,Full,0.01010,0.00000,HighVdiv,0.01000,1.0115,1.152471,0.000159,0.198412, 793,225:800E-3;280:500E-3;330:420E-3;382:380E-3;430:350E-3;477:330E-3;511:320E-3;553:280E-3;595:270E-3;639:250E-3;703:240E-3;767:220E-3;799:215E-3;831:205E-3;863:200E-3;895:190E-3;959:170E-3;1.023E+3:100E-3,0:0E-6;,243,-0.0351;-0.0263;-0.0176;-0.0088;-0.0000;0.0088;0.0175;0.0263;0.0351,-0.0352;-0.0266;-0.0178;-0.0089;0.0001;0.0091;0.0180;0.0269;0.0354,1,1,1,1,1'
current_grid_df = maingrid.data
data = []
for x in newrow.split('\n'):
    if len(x) > 10:
        data.append(x.split(',')) 
index_list = []
data_list = []
for index_row, data_val in enumerate(data):
    index = int(data_val[0])+index_row
    index_list.append(index)
    data_temp = data_val[1:] 
    data_list.append(data_temp)
additional_row = pd.DataFrame(data_list, columns=current_grid_df.columns, index=index_list)
df_to_add = pd.concat([current_grid_df, additional_row], ignore_index=False)
maingrid.data = df_to_add   # Adding the row here
 
```
I get 2 types of output everytime I run it... This seems to be generated randomly every time i run the cell.

Random output1:  Column width is messed up
![image](https://github.com/bloomberg/ipydatagrid/assets/73568181/6a7facc1-4f31-49ea-aab7-8aa61c00e7b4)

Random output2:  Column width is correct
![image](https://github.com/bloomberg/ipydatagrid/assets/73568181/98d6dd55-345c-42ab-a4ea-4e4051306f67)

**Comment by jgunstone** [comment]
hi - 
if you set data in the way that you have, i.e.: 
`mygrid.data = df_new`
you are effectively reinitialising the grid - you could give it a whole new dataframe with different col names when doing this. 
as such it doesn't resets behaviour you had previously applied.
you can either: 
- record the col widths before you set the grid and then reset them after (probs easiest) 
- use the `set_cell_value` method to set the values of the cells you want to change. this is probably the "cleanest" method as it just updates the data in-place without re-initialising the whole grid.

**Comment by jobinnthomas** [comment]
> hi - if you set data in the way that you have, i.e.: `mygrid.data = df_new` you are effectively reinitialising the grid - you could give it a whole new dataframe with different col names when doing this. as such it doesn't resets behaviour you had previously applied. you can either:
> 
> * record the col widths before you set the grid and then reset them after (probs easiest)
> * use the `set_cell_value` method to set the values of the cells you want to change. this is probably the "cleanest" method as it just updates the data in-place without re-initialising the whole grid.

Thanks for the suggestions. 

For using 'set_cell_value'
I do know the number of rows before hands...So maybe I could create the Datagrid with the known number of rows, all blank 
and then resize the height of the datgrid to avoid showing them even. Then i could set the cells one by one.

For the other option of resetting the grid, I put maingrid grid in a ipywidget tab with vertical HBox. I am not showing that below. but I want to update that maingrid in the tab with vertical HBox. So are you suggesting something like below?
If not could you help elaborate on your answer.
 
 ```
# Initialize the Grid...
df = pd.DataFrame(data={"Index": [''], "RepeatIndex": ['']}, index=["Index", "RepeatIndex"])  # Assuming a single value
maingrid = ipygrid.DataGrid(df, selection_mode='cell', editable=True, layout=widgets.Layout(
    width="2000px", height="500px", margin='0px 0px 0px 0px'))
maingrid.auto_fit_columns = True
maingrid.auto_fit_params = {"area": "all"}


# Get the updated rows
df =.....

# Create another grid maingrid_1 and assign the rows to this grid..
maingrid_1 = ipygrid.DataGrid(df, selection_mode='cell', editable=True, layout=widgets.Layout(
    width="2000px", height="500px", margin='0px 0px 0px 0px'))
maingrid_1 .auto_fit_columns = True
maingrid_1 .auto_fit_params = {"area": "all"}

## Rewrite the maingrid to this grid...to update the original grid thats already display.
maingrid = maingrid_1

```

**Comment by jgunstone** [comment]
just checked this - 
it doesn't look like it resets the col widths if the dataframe is the same 

![ipydatagrid](https://github.com/bloomberg/ipydatagrid/assets/21370980/41ef364e-c0f2-4e79-af15-e11a4fbe6a08)

```py
import pandas as pd
import ipydatagrid as DataGrid

df = pd.DataFrame({"a": [1,2], "b": [3,4]})
df1 = pd.DataFrame({"a": [3,4], "b": [5,6]})
gr = DataGrid(df, column_widths = {"a": 20})
gr
```

```py
gr.data = df1
```

**Comment by jobinnthomas** [comment]
Try the example I provided.......Do you see what I see? 
If you don't, can you provide me your requirements file.....

**Comment by ollyhensby** [comment]
Hi @jobinnthomas, In your requirements.txt you are using `ipydatagrid==1.1.15`

Try updating to the latest release [1.2.1](https://github.com/bloomberg/ipydatagrid/releases/tag/1.2.1) where I resolved the issue of column widths resetting when setting new data if `auto_fit_columns` is set to True.

Here is the PR fixing that issue: https://github.com/bloomberg/ipydatagrid/pull/452

**Comment by jobinnthomas** [comment]
> Hi @jobinnthomas, in your requirements.txt you are using `ipydatagrid==1.1.15`
> 
> Try updating to the latest release [1.2.1](https://github.com/bloomberg/ipydatagrid/releases/tag/1.2.1) where I resolved the issue of column widths resetting when setting new data if `auto_fit_columns` is set to True.
> 
> Here is the PR fixing that issue: #452

Thanks..Yes i can confirm the issue is fixed..I am using the following and it works.
notebook==7.0.8
voila==0.5.5
ipywidgets==8.1.1 
ipydatagrid==1.2.1
ipynb==0.5.1 

[reqAcq.txt](https://github.com/bloomberg/ipydatagrid/files/14304711/reqAcq.txt)
