### ISSUE TITLE
Missing NPM publish on 1.2.1

### ISSUE THREAD

**Issue by doddsiedodds** [bloomberg/ipydatagrid#474]
**Describe the bug**
The JavaScript bundle for version 1.2.1 has not been released and so trying to retrieve the UI code from the cdn fails

**Comment by martinRenou** [comment]
Thanks for reporting I'll look into publishing it

**Comment by martinRenou** [comment]
https://www.npmjs.com/package/ipydatagrid/v/1.2.1
