### ISSUE TITLE
html exports that depend on javascript fetched from cdn no longer render

### ISSUE THREAD

**Issue by cmichal2** [bloomberg/ipydatagrid#505]
I have some jupyter notebook widgets built with ipydatagrid which used to render nicely when using the notebook File->Export as->HTML

Now, these exported notebooks no longer render properly. Even .html files that used to work, no longer render.

Looking in firefox's javascript console, I see the browser starts by complaining:
```
Loading failed for the <script> with source “file:///home/zzz/Downloads/ipydatagrid.js”.
```
(which I believe is expected) and then it says:
```
Falling back to https://cdn/jsdelivr.net/npm/ for ipydatagrid^1.1.16
https://cdn.jsdelivr.net/npm/ipydatagrid@^1.1.16/dist/index.js
```
So far so good, I think, but then:
```
Error: Failed to deserialize data
    e https://cdn.jsdelivr.net/npm/ipydatagrid@^1.1.16/dist/index.js:2
    deserialize https://cdn.jsdelivr.net/npm/ipydatagrid@^1.1.16/dist/index.js:2
    _deserialize_state https://unpkg.com/@jupyter-widgets/html-manager@*/dist/embed-amd.js:2
    _make_model https://unpkg.com/@jupyter-widgets/html-manager@*/dist/embed-amd.js:16
    new_model https://unpkg.com/@jupyter-widgets/html-manager@*/dist/embed-amd.js:16
    set_state https://unpkg.com/@jupyter-widgets/html-manager@*/dist/embed-amd.js:16
    set_state https://unpkg.com/@jupyter-widgets/html-manager@*/dist/embed-amd.js:16
    promise callback*set_state https://unpkg.com/@jupyter-widgets/html-manager@*/dist/embed-amd.js:16
    I https://unpkg.com/@jupyter-widgets/html-manager@*/dist/embed-amd.js:26
    I https://unpkg.com/@jupyter-widgets/html-manager@*/dist/embed-amd.js:26
    I https://unpkg.com/@jupyter-widgets/html-manager@*/dist/embed-amd.js:26
    I https://unpkg.com/@jupyter-widgets/html-manager@*/dist/embed-amd.js:26
    promise callback*I https://unpkg.com/@jupyter-widgets/html-manager@*/dist/embed-amd.js:26
    <anonymous> https://unpkg.com/@jupyter-widgets/html-manager@*/dist/embed-amd.js:29
    execCb https://cdnjs.cloudflare.com/ajax/libs/require.js/2.1.10/require.min.js:29
    check https://cdnjs.cloudflare.com/ajax/libs/require.js/2.1.10/require.min.js:18
    enable https://cdnjs.cloudflare.com/ajax/libs/require.js/2.1.10/require.min.js:23
    init https://cdnjs.cloudflare.com/ajax/libs/require.js/2.1.10/require.min.js:17
    g https://cdnjs.cloudflare.com/ajax/libs/require.js/2.1.10/require.min.js:26
    setTimeout handler*h.nextTick< https://cdnjs.cloudflare.com/ajax/libs/require.js/2.1.10/require.min.js:32
    g https://cdnjs.cloudflare.com/ajax/libs/require.js/2.1.10/require.min.js:26
    requirejs https://cdnjs.cloudflare.com/ajax/libs/require.js/2.1.10/require.min.js:31
    <anonymous> https://unpkg.com/@jupyter-widgets/html-manager@*/dist/embed-amd.js:29
    <anonymous> https://unpkg.com/@jupyter-widgets/html-manager@*/dist/embed-amd.js:29
[embed-amd.js:16:1002392](https://unpkg.com/@jupyter-widgets/html-manager@*/dist/embed-amd.js)
    _make_model https://unpkg.com/@jupyter-widgets/html-manager@*/dist/embed-amd.js:16
    new_model https://unpkg.com/@jupyter-widgets/html-manager@*/dist/embed-amd.js:16
    set_state https://unpkg.com/@jupyter-widgets/html-manager@*/dist/embed-amd.js:16
    set_state https://unpkg.com/@jupyter-widgets/html-manager@*/dist/embed-amd.js:16
    (Async: promise callback)
    set_state https://unpkg.com/@jupyter-widgets/html-manager@*/dist/embed-amd.js:16
    I https://unpkg.com/@jupyter-widgets/html-manager@*/dist/embed-amd.js:26
    I https://unpkg.com/@jupyter-widgets/html-manager@*/dist/embed-amd.js:26
    I https://unpkg.com/@jupyter-widgets/html-manager@*/dist/embed-amd.js:26
    I https://unpkg.com/@jupyter-widgets/html-manager@*/dist/embed-amd.js:26
    (Async: promise callback)
    I https://unpkg.com/@jupyter-widgets/html-manager@*/dist/embed-amd.js:26
    <anonymous> https://unpkg.com/@jupyter-widgets/html-manager@*/dist/embed-amd.js:29
    execCb https://cdnjs.cloudflare.com/ajax/libs/require.js/2.1.10/require.min.js:29
    check https://cdnjs.cloudflare.com/ajax/libs/require.js/2.1.10/require.min.js:18
    enable https://cdnjs.cloudflare.com/ajax/libs/require.js/2.1.10/require.min.js:23
    init https://cdnjs.cloudflare.com/ajax/libs/require.js/2.1.10/require.min.js:17
    g https://cdnjs.cloudflare.com/ajax/libs/require.js/2.1.10/require.min.js:26
    (Async: setTimeout handler)
    nextTick https://cdnjs.cloudflare.com/ajax/libs/require.js/2.1.10/require.min.js:32
    g https://cdnjs.cloudflare.com/ajax/libs/require.js/2.1.10/require.min.js:26
    requirejs https://cdnjs.cloudflare.com/ajax/libs/require.js/2.1.10/require.min.js:31
    <anonymous> https://unpkg.com/@jupyter-widgets/html-manager@*/dist/embed-amd.js:29
    <anonymous> https://unpkg.com/@jupyter-widgets/html-manager@*/dist/embed-amd.js:29
```

The javascript file exists and can be downloaded, but doesn't seem to work.

Google Chrome gives similar errors:
```
embed-amd.js:16 Error: Failed to deserialize data
    at Object.e [as deserialize] (index.js:2:780772)
    at Object.deserialize (index.js:2:2504501)
    at v._deserialize_state (embed-amd.js:2:373454)
    at $n._make_model (embed-amd.js:16:1002558)
```

If instead I copy nbextensions/ipydatagrid/index.js to ipydatagrid.js and put it in the same directory as my exported html file, the browser finds the local file and the widgets render properly.

I'm using ipydatagrid 1.1.16, but have tried 1.2.1 and 1.3.0 as well with the same result.

Has something changed in the javascript that is distributed via cdn.jsdelivr.net ?

**Environment (please complete the following information):**
I'm using 
 - Gentoo linux, also tried on windows.
 - firefox 115.7 and chrome 121.0.6167.184

**Comment by cmichal2** [comment]
Digging a little more, I think I see where the issue is.

The version specification from ipydatagrid that ends up in the html file is: "^1.1.16" so the cdn provides the latest with the same major version number, 1.3.0, which doesn't seem to be compatible with the output from 1.1.16. It does seem to work now with output from 1.3.0 widgets - perhaps I hadn't restarted my jupyter server before exporting.

Unfortunately though, exports made with older versions don't seem to work. So I have a couple of questions:
- is there a way to change how the version shows up in the export, and demand a specific version, rather than the latest?
- is there a way to fix this so that old exports continue to work properly - like remove 1.3.0 from the cdn and rename it to 2.0.0 since it seems to be incompatible with the 1.1.x output?

**Comment by cmichal2** [comment]
Looking further I see that if I remove the ^ in _frontend.py then the ^ disappears from the exported html - so that change would fix future problems like this, but still leaves all past exports with <1.3.0 broken. Would it be possible to delete 1.3.0, or to somehow make its javascript backwards compatible?

**Comment by martinRenou** [comment]
Thanks for opening an issue. Indeed the pulled CDN version will not be compatible with what you exported. You may need to re-run the export. Sorry for the inconvenience.

**Comment by cmichal2** [comment]
Thanks for the response!

The use case here makes re-exporting awkward. Students in a course have been turning in assignments all term using html exports with 1.1.16. Re-exporting several thousand assignments from a few hundred students isn't that easy!

It seems a bit bad to have an update to something 'in the cloud' break old documents. I think in the future it really would be best to either remove the ^ in _frontend.py so that the version is locked in (I've done that on our servers now so future exports don't get broken), or insist that incompatible changes have a new major version number.

Is there is a way to fix this globally for existing exports? Presumably there may be exports out there with 1.3.0 that would be broken by removing it - though probably few compared to older versions.

**Comment by martinRenou** [comment]
I totally agree with what you are saying. I will look into making a patch that fixes the backward incompatibility.

**Comment by martinRenou** [comment]
I opened a PR https://github.com/bloomberg/ipydatagrid/pull/507 that should fix support for serialized models using ipydatagrid <=1.2.1. 

> I think in the future it really would be best to either remove the ^ in _frontend.py so that the version is locked in

I'd personally prefer not to, it's good to be loose about the version that is used (as long as the front-end version support the serialized model 😅).

> It seems a bit bad to have an update to something 'in the cloud' break old documents
> [...]
> insist that incompatible changes have a new major version number

Yes and yes, totally agree. Sorry for the inconvenience!

**Comment by cmichal2** [comment]
I see 1.3.1 is out and the old files render properly again. Thanks so much for fixing this!
